Kinga_Straszkiewicz_LaTeX
nlp-ug-2018-19/LaTeX-homework pull request #7
Opened 2019-06-06 09:46 UTC by kingastraszkiewicz

2019-06-07 14:56 UTC, MarcinFortuna-UG requested changes
Dear Kinga,

first of all, please rename the files so that they contain your name. Apart from this, please correct some minor things listed inline.

2019-06-07 14:56 UTC, MarcinFortuna-UG commented on main.tex
> +\section{Section1}
Why no space between section and the numeral?

2019-06-07 14:56 UTC, MarcinFortuna-UG commented on main.tex
> +\textipa{/"maI "neIm Iz "kIngA. "aI "aem @ "stju:d@nt @t @ jUnI"v3:s@ti @v "gdansk. "maI "Int@r@sts "Inklu:d lIn"gwIstIks, I"spES@li f@"n6l@dZi aend "graem@r, b@t "6lseU "6rIdZIn @v "laengwIdZ "aend
1. Please eliminate periods, there is no punctuation in transcription!
2. a university? The university.
3. in'clude
4. linguistics - velar nasal
5. there is a symbol for ash in tipa
6. also - long vowel; the diphthong looks different too
7. language, and, programming - correct the ash; language has a velar nasal

2019-06-07 14:56 UTC, MarcinFortuna-UG commented on main.tex
> +\textipa{"mam na "imjE "kjinga. "jEs\|[tEm s\|[tu"\|[dEn\|[tk\~O u\|[ni"vEr\|[s1\|[te\|[tu g\|[da\textltailn"scegO. \|[dO "mOix \|[zai\|[n\|[tErE"\|[sOva\textltailn \addspace\|[za"li\t{t\k{s}}a C\~E
1. uniwersytetu - which syllable will be stressed?
2. kjinga - please make [j] a diacritic
3. również - no [ni], please transcribe the patal nasal
4. of course, eliminate periods ;)

2019-06-11 14:26 UTC, MarcinFortuna-UG commented
Dear Kinga, within the same pull request, please *remove* your old files in another commit. If I merged at this point, 4 new files would be added to the master branch.

2019-06-11 16:57 UTC, MarcinFortuna-UG approved these changes
👍

2019-06-11 16:57 UTC, merged

2019-06-11 17:18 UTC, kingastraszkiewicz commented
Thank you :)